version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: erp-nginx
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
      - mongodb
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: erp
      MYSQL_USER: erp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis-erp
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel
  mongodb:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - "./data/mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: laravel
    ports:
      - "27018:27017"
    networks:
      - laravel
